#[test]
fn apple_bridge_header_is_generated_by_cbindgen() {
    let header =
        include_str!("../apple/macos/Sources/AshenFrontierBridge/include/ashen_frontier.h");

    assert!(header.contains("generated by cbindgen"));
    assert!(header.contains("af_world_move_units"));
}
