/* This file is generated by cbindgen. Do not edit by hand. */

#ifndef ASHEN_FRONTIER_H
#define ASHEN_FRONTIER_H

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>

#define AF_COMMAND_STATUS_ACCEPTED 0

#define AF_COMMAND_STATUS_EMPTY_SELECTION 1

#define AF_COMMAND_STATUS_DESTINATION_OUT_OF_BOUNDS 2

#define AF_COMMAND_STATUS_BLOCKED_DESTINATION 3

#define AF_COMMAND_STATUS_NO_PATH 4

#define AF_COMMAND_STATUS_UNKNOWN_UNIT 5

#define AF_COMMAND_STATUS_INVALID_UNIT_LIST 100

#define AF_UNIT_KIND_WORKER 0

#define AF_UNIT_KIND_RANGER 1

#define AF_UNIT_KIND_SOLDIER 2

typedef struct AfWorld AfWorld;

typedef struct AfEntityPosition {
  uint32_t id;
  uint32_t kind;
  float health;
  float x;
  float y;
} AfEntityPosition;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

struct AfWorld *af_world_create(uint16_t width, uint16_t height);

void af_world_destroy(struct AfWorld *world);

void af_world_step(struct AfWorld *world, uint32_t steps);

void af_world_spawn_horde(struct AfWorld *world, uint32_t enemy_count);

uint32_t af_world_spawn_unit(struct AfWorld *world, uint32_t unit_kind);

uint32_t af_world_move_units(struct AfWorld *world,
                             const uint32_t *unit_ids,
                             size_t unit_count,
                             float destination_x,
                             float destination_y);

uint64_t af_world_tick(const struct AfWorld *world);

size_t af_world_unit_count(const struct AfWorld *world);

size_t af_world_enemy_count(const struct AfWorld *world);

size_t af_world_read_units(const struct AfWorld *world,
                           struct AfEntityPosition *out_positions,
                           size_t capacity);

size_t af_world_read_enemies(const struct AfWorld *world,
                             struct AfEntityPosition *out_positions,
                             size_t capacity);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* ASHEN_FRONTIER_H */
